version: "3.1"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Africa/Cairo
    volumes:
      - .\n8n_data:/home/node/.n8n
